name: Merge Schedule

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: '*/5 * * * *'

# 💡 關鍵：直接在腳本裡跟 GitHub 申請這兩項權限，就不用去動網頁設定了！
permissions:
  contents: write
  pull-requests: write

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          merge_method: squash
          time_zone: 'Asia/Taipei'
          require_statuses_success: 'false'
          automerge_fail_label: 'merge-schedule-failed'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
