name: Merge Schedule

on:
  # 💡 加上這行，網頁上就會立刻多出一顆手動執行的按鈕，不用再等 GitHub 的大塞車公車
  workflow_dispatch:

  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: '*/5 * * * *'

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          merge_method: squash
          time_zone: 'Asia/Taipei'
          require_statuses_success: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
